### ISSUE TITLE
FetchMedia error

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow#29]
I'm not sure how this happened, but it looks like `get_block_size` is throwing an error sometimes when n is negative?

```
Runtime error:
Traceback (most recent call last):
  File "/opt/docnow/lib/python3.5/site-packages/luigi/worker.py", line 181, in run
    new_deps = self._run_get_new_deps()
  File "/opt/docnow/lib/python3.5/site-packages/luigi/worker.py", line 119, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/docnow/dnflow/summarize.py", line 355, in run
    update_block_size = get_block_size(count, 5)
  File "/home/docnow/dnflow/summarize.py", line 72, in get_block_size
    return int(n / (math.ceil(math.log10(n)) * d))
ValueError: math domain error
```

![screen shot 2016-08-19 at 4 21 05 pm](https://cloud.githubusercontent.com/assets/33829/17823177/2eeb3958-6629-11e6-8575-61070d9ba93a.png)

**Comment by dchud** [comment]
Similar problem, new traceback:

``` python
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/dnflow-3.5.1-env/lib/python3.5/site-packages/luigi/worker.py", line 181, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/var/pyenv/versions/dnflow-3.5.1-env/lib/python3.5/site-packages/luigi/worker.py", line 119, in _run_get_new_deps
    task_gen = self.task.run()
  File "/Users/dchud/projects/docnow/dnflow/summarize.py", line 378, in run
    if len(hashes) % update_block_size == 0:
ZeroDivisionError: integer division or modulo by zero
```

Note that this occurred on a search that matched 625 tweets which referenced two media files and only successfully captured one media file.
